version: "3.8"

services:
  db:
    image: postgres:16
    container_name: todo_db
    environment:
      - POSTGRES_DB=todo_db
      - POSTGRES_USER=todo_user
      - POSTGRES_PASSWORD=todo_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todo_user -d todo_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: idoshoshani123/my-todo-app:latest
    container_name: todo_app
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=todo_db
      - DATABASE_USER=todo_user
      - DATABASE_PASSWORD=todo_password
      - DATABASE_PORT=5432
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
